### ISSUE TITLE
Enhancement: 시각 표시 ui 수정

### ISSUE THREAD

**Issue by kdh8219** [serafuku/neo-quesdon#12]
여타 메신저들처럼, 년•월•일을 상단에 표시하고, 질문과 답변에는 시각만 적는건 어떨까요?

**Comment by yunochi** [comment]
안 그래도 시간 표시를 어떤 식으로 할지 고민중이에요. 제 취향은 지금과 똑같이 하되, 브라우저 타임존만 반영하는건데 좀 고민해봐야 할듯?

**Comment by yunochi** [comment]
![image](https://github.com/user-attachments/assets/e3abbbac-ab2f-4f39-95d8-80e57612649f)
브라우저 타임존 24시간제로 보여주도록 바꿔뒀습니다
