### ISSUE TITLE
메인 페이지 표시 여부 선택

### ISSUE THREAD

**Issue by hawa-takakura** [serafuku/neo-quesdon#122]
기본값을 정하고 답변별로 바꿀 수 있으면 좋겠어요!

딱히 보여지고 싶지 않은 사람도 있을거고, 어떤 답변만 보여주고 싶지 않을 수도 있고, 역으로 어떤 답변만 보여주고 싶은 사람도 있을 수 있지 않을까요?

지금은 공개 범위 설정과 무관하게 표시되고 있어서 원치 않게 보여질 수도 있다고 생각해요!

**Comment by yunochi** [comment]
이거 안 그래도 한번 이야기가 있긴 했는데 좀 UI적으로 구현하기 애매해서 안 한거긴 해요. 
답변에 공개범위 버튼이 두개가 있는건 혼동을 가져오기 쉬울것 같아서 말이죠. 
좀 다른 이야기지만 NSFW 플래그된 답변은 메인 페이지에서는 숨기는 것을 고려하고 있긴 해요.

**Comment by Squarecat-meow** [comment]
#128 에서 작업중입니다!

**Comment by yunochi** [comment]
완료!
