### ISSUE TITLE
프록시 적용 이후 일부 프로필 사진 깨짐

### ISSUE THREAD

**Issue by kdh8219** [serafuku/neo-quesdon#123]
![Screenshot_20241221_123114_Firefox](https://github.com/user-attachments/assets/1864f8b8-e9d9-4efc-94c9-2223a29fcd5a)

**Comment by kdh8219** [comment]
#23

**Comment by yunochi** [comment]
이거 아마도 리모트 이미지 서버가 헤더를 잘못 준게 문제긴 한데요...  (Content-Type 헤더가 image종류가 아니면 뱉게 해놨음)
일단 이런식으로 수정은 해 봤습니다 https://github.com/serafuku/neo-quesdon/pull/126

**Comment by yunochi** [comment]
해결된 것 같아요
