### ISSUE TITLE
모바일 환경 알림창 줄넘김 이슈

### ISSUE THREAD

**Issue by kdh8219** [serafuku/neo-quesdon#124]
![Screenshot_20241221_123438_Firefox](https://github.com/user-attachments/assets/d65a58a9-bfe8-4858-b87e-4d8953d8dea9)
![Screenshot_20241221_123448_Firefox](https://github.com/user-attachments/assets/454d7bfd-11b8-4929-98ff-f2740c992e31)

**Comment by yunochi** [comment]
https://github.com/serafuku/neo-quesdon/pull/127
로 해결되었다고 해요
