### ISSUE TITLE
답변이 로딩중일때 에러메시지가 표시되는 현상

### ISSUE THREAD

**Issue by kdh8219** [serafuku/neo-quesdon#129]
아직 답변이 로딩중일때 '찾으시는 답변이 없어요!'라는 오류메시지가 보이다가 로딩 된 이후 답변이 보입니다.
답변이 없는것이 확실하지 않은 상황에서는 안띄우는게 더 좋을 것 같습니다.

**Comment by kdh8219** [comment]
역시 next식은 후자 아닐까요

**Comment by yunochi** [comment]
이게 원래는 저 `찾으시는 답변이 없어요!` 텍스트 자체가 없었어서 저런 문제는 없었는데 이번에 추가하면서 생긴 예상 못한 부작용이네요...<
이건 적당히 해결해 볼게요<

**Comment by yunochi** [comment]
완료!
