### ISSUE TITLE
유저 차단 연동하기

### ISSUE THREAD

**Issue by kdh8219** [serafuku/neo-quesdon#22]
사이버불링 방지용 기능이 필요할 것 같습니다.

- 차단한 유저의 질문을 자동으로 거절
- 차단한 유저의 답변을 타임라인에서 가리기

**Comment by yunochi** [comment]
익명질문 안 받기를 설정한 경우에만 의미가 있을것 같긴 한데 좋은 아이디어 같네요!

**Comment by yunochi** [comment]
차단 기능을 구현 완료했어요! 
일단 이 이슈는 닫고, 나중에 이걸로 모자란것 같으면 다시 꺼내서 보완해볼까 해요

**Comment by kdh8219** [comment]
미스키/마스토돈과 연동하는 부분은 구현하지 않을 예정인건가요?

**Comment by yunochi** [comment]
> 미스키/마스토돈과 연동하는 부분은 구현하지 않을 예정인건가요?

아 실수로 다른 이슈랑 착각해서 잘못 닫음; 이건 조만간 할까 싶어요

**Comment by kdh8219** [comment]
네. 감사합니다.
차단해둔 유저들이 언제 네오 퀘스돈에 가입할지도 모르는 일이거니와, 한 번 더 얼굴 보는것도 고통스럽고 하여, 빠른 구현 부탁드립니다
