### ISSUE TITLE
계정 이름의 이모지를 프록시를 통해 제공하기

### ISSUE THREAD

**Issue by kdh8219** [serafuku/neo-quesdon#23]
현재 동작은 이모지를 클라이언트가 인스턴스에서 직접 가져오고있습니다.
하지만, 인스턴스가 신뢰 불가능한 상황에 문제가 될 수 있습니다.
프록시등의 보호장치가 필요할 것이라 생각합니다.

**Comment by yunochi** [comment]
해냈습니다!!
