### ISSUE TITLE
빠른 답변: 선인장에게 답변하기

### ISSUE THREAD

**Issue by kdh8219** [serafuku/neo-quesdon#39]
![screenshot-2024-11-23-21:15:16](https://github.com/user-attachments/assets/80a34d34-8bc7-4340-89d9-56776edde139)
질문을 알려주는 우리의 친구 선인장에게
![screenshot-2024-11-23-21:16:55](https://github.com/user-attachments/assets/bc77a141-7663-407f-85b7-0571f8094e4f)
이렇게 답변을 쓰면, 자동으로 연동되서 답변되게 하는건 어떨까요?

**Comment by Squarecat-meow** [comment]
이렇게 하면 봇을 하나 더 만드는게 더 빠를 정도로 구현이 까다로워서... 그리고 웹을 일부러 만든 의의도 흐려지네요

**Comment by kdh8219** [comment]
확실히 그렇긴 하네요

**Comment by yunochi** [comment]
백앤드에서 알림이 왔는지 선인장 계정을 체크하고 있어야 해서 구현이 좀 까다롭기도 하고, 공개범위 등의 설정은 또 불가능해서 저도 좀 굳이....? 라는 생각입니다.
