### ISSUE TITLE
알림에 질문자 표시

### ISSUE THREAD

**Issue by kdh8219** [serafuku/neo-quesdon#40]
선인장이 dm으로 알림을 줄 때 질문자도 알려주면 좋겠습니다.

**Comment by kdh8219** [comment]
멘션이 문제라면 \`로 감싸거나 \@를 지우면 어떨까요?

**Comment by yunochi** [comment]
이건 한번 직접 구현 가보실래요? ㄱ?

**Comment by kdh8219** [comment]
`assigned` 메시지 보자마자 테스트중입니다 ㅋㅋㅋㅋㅋ

**Comment by yunochi** [comment]
이번에는 풀리퀘 develop 타겟으로 넣어주세요ㅋㅋㅋㅋ 저번에 main으로 넣으셨더라고요<

**Comment by kdh8219** [comment]
:ok:
