### ISSUE TITLE
괴롭힘 등의 악용방지를 위한 기능

### ISSUE THREAD

**Issue by yunochi** [serafuku/neo-quesdon#57]
## 익명 질문을 통한 괴롭힘에 대비하기 위한 기능
<del>
- 익명으로 질문할 경우 괴롭힘 등의 악용에 대비해 Request 헤더를 question 테이블에 기록
  - 질문자 공개로 질문할때는 기록할 필요가 없어서 기록하지 않음
- 개인정보 보호를 위해서 답변이 완료되거나, 질문이 삭제되면 기록된 내용은 없어지도록 구현 
</del>

* 헤더 기록은 크게 의미가 없을것 같아서 유저차단 기능을 구현하는게 우선일 것 같음

**Comment by seojangho** [comment]
진지한 검토 없이 생각만 해봤습니다.

### 1

- 익명 질문시 질문자 아이피를 보관 (어느 사용자에게도 보여지지 않음)
- 답변을 하려는 사용자가 답변을 하는 대신 "이 아이피로부터 질문 x일간 받지 않기" 를 고를 수 있음
- 사용자가 그러한 액션을 취하지 않고, 정상적으로 답변을 한다면 보관된 아이피는 즉시 삭제
- 사용자가 어떠한 액션을 취하지 않고 일주일이 지나도 아이피는 삭제 (그러면 "이 아이피로부터 질문 x일간 받지 않기" 를 고를 수 없음)

### 2

- 질문에 특정 키워드가 있다면 조용히 버리는 기능 추가?

**Comment by yunochi** [comment]
> 진지한 검토 없이 생각만 해봤습니다.
> ### 1
> 
>     * 익명 질문시 질문자 아이피를 보관 (어느 사용자에게도 보여지지 않음)
> 
>     * 답변을 하려는 사용자가 답변을 하는 대신 "이 아이피로부터 질문 x일간 받지 않기" 를 고를 수 있음
> 
>     * 사용자가 그러한 액션을 취하지 않고, 정상적으로 답변을 한다면 보관된 아이피는 즉시 삭제
> 
>     * 사용자가 어떠한 액션을 취하지 않고 일주일이 지나도 아이피는 삭제 (그러면 "이 아이피로부터 질문 x일간 받지 않기" 를 고를 수 없음)
> 
> 
> ### 2
> 
>     * 질문에 특정 키워드가 있다면 조용히 버리는 기능 추가?

IP정보가 크게 의미가 있지 않을것 같아서 좀 애매할 것 같아요. 
셀룰러 네트워크등으로 접속하는 사람은 캐리어 NAT때문에 ip가 고유하지도 않고 오히려 오차단의 위험성이 클것 같습니다. 
사실 그런 의미에서 헤더를 기록하는 것도 VPN을 싹 막을게 아니라면 크게 의미가 있을것 같지 않아서 좀 미묘하네요. 

차라리 '익명질문 안 받기' 기능과 별개로 '비로그인 사용자 질문 안 받기' 기능을 만드는건 어떨까 하는 생각이 들었어요. 
익명으로 질문할 수는 있지만 로그인을 해야 질문을 할 수 있도록 하는 식? 
그럼 '이 질문자 차단하기' 같은 기능도 좀 더 신뢰성있게 구현 가능할 것 같고요

**Comment by seojangho** [comment]
질문을 받는 입장에서 '익명질문 안 받기' 나  '비로그인 사용자 질문 안 받기' 같은 옵션을 보다 적극적으로 쓸 수 있게 유도하려려면  'x일동안 비로그인 사용자 질문 안 받기' 와 같이 기간제로 할 수 있는 옵션을 추가하면 좋을것 같아요. 당장의 괴롭힘에 시달리는 사람이 있다 하더라도, 이 옵션이 수동으로 되돌리지 않으면 반영구적으로 적용된다고 하면 사람 성격에 따라서 선뜻 켜기 어려워할 수 있을것 같아요.

별개로, 현재 괴롭힘 문제가 네오-퀘스돈에 실제로 있는지 없는지 파악하는 메커니즘이 우선일수도 있습니다. 그런 면에서 가장 시급한 기능은 "이 질문 무시하고 신고하기" 버튼일 수도 있어요.

**Comment by yunochi** [comment]
사람마다 받고싶지 않은 질문이 다를것이고, 모더레이션의 부담 문제도 있을것 같아서 신고 기능보다는 차단 기능을 구현하는게 나을것 같다는 쪽으로 생각이 가고 있습니다. 
일단 익명질문 안받기 기능은 이미 있으니 유저차단 기능만 구현해도 어느정도는 유효할 갓 같네요.

**Comment by kdh8219** [comment]
#22

**Comment by kdh8219** [comment]
질문이 불링일 가능성을 고려해야한다면, 작성자가 답변하지 않고 삭제한 질문들을 db에 잠시 보관할 필요도 있다고 생각합니다. 관리자가 불링 여부를 검사한다던지, 기록을 남긴다던지 할 필요가 있으리라 생각해요.

**Comment by yunochi** [comment]
> 질문이 불링일 가능성을 고려해야한다면, 작성자가 답변하지 않고 삭제한 질문들을 db에 잠시 보관할 필요도 있다고 생각합니다. 관리자가 불링 여부를 검사한다던지, 기록을 남긴다던지 할 필요가 있으리라 생각해요.

일단 차단기능 자체는 지금 만들어보고 있어요.

**Comment by yunochi** [comment]
차단 기능을 구현 완료했어요!
일단 이 이슈는 닫고, 나중에 이걸로 모자란것 같으면 다시 꺼내서 보완해볼까 해요
