### ISSUE TITLE
Bug: 구버전 미스키 사용의 닉네임의 커스텀 이모지가 이미지로 치환되지 않음

### ISSUE THREAD

**Issue by kdh8219** [serafuku/neo-quesdon#58]
[![Screenshot_20241129_200555_Firefox](https://github.com/user-attachments/assets/b2b79128-e037-4cf4-b7aa-4732e0b18d66)](https://neo-quesdon.serafuku.moe/main/user/@Emest@madost.one)

**Comment by kdh8219** [comment]
아마도 #23을 해결하면 자연히 해결될 것 같습니다

**Comment by kdh8219** [comment]
> > 아마도 #23 을 구현하면 자연히 해결될 것 같습니다
> 
> 그건 아니고, 커모지 받아오는 API부터 다른것 같아요. 로그 보면 커모지 URL알아내는 부분부터 터져요

:아이고: 전 또 로그인때랑 같은 cors쪽일줄 알았네요

**Comment by yunochi** [comment]
이것도 해결하긴 해야하는데 일단 로그인만 고쳐놓고 우선순위에서 밀려서 못 하고 있네요

**Comment by yunochi** [comment]
> #120의 PR에서 해결되었을 것 같은데, 업데이트 된 이후에 확인해보면 될 것 같아요! 아직 적용은 안된 것 같네요.

이제 업데이트 했는데, 마도 계정 쓰는 사람중에 누군가가 접속해봐야 알 수 있을것 같아요! 프로필이 업데이트 되는 시점에 접속했을때라서...<

**Comment by yunochi** [comment]
해결 되었다고 해요!
