### ISSUE TITLE
Bug: 차단 버튼이 모바일 환경에서 프로필 아이콘에 가려짐

### ISSUE THREAD

**Issue by kdh8219** [serafuku/neo-quesdon#61]
![Screenshot_20241130_214153_Firefox](https://github.com/user-attachments/assets/d51786f0-404a-41f7-9ca0-3e5a448db01f)

**Comment by yunochi** [comment]
초고속 핫픽스 완료했어요

**Comment by kdh8219** [comment]
0398acbbd561b87c3929703488248f14253f3e6c

**Comment by kdh8219** [comment]
![Screenshot_20241205_233523_Firefox](https://github.com/user-attachments/assets/794d19d6-134e-4252-aec2-b0e63ae4e07d)
작동은 하는 것 같은데 이번엔 프로필 한가운데를 가리네요
