### ISSUE TITLE
github 링크 접근성 관련

### ISSUE THREAD

**Issue by kdh8219** [serafuku/neo-quesdon#63]
현재 github로 통하는 링크가 `/`에만 있는데, 유효한 토큰을 가진 상태로 `/`에 접속하면 `/main`으로 이동되어, github에 접근하기 힘듭니다.
`/main/settings`등에도 footer를 추가하여 더 쉽게 찾을 수 있도록 하는것을 제안합니다.

**Comment by Squarecat-meow** [comment]
저는 굳이... 싶어요 대부분의 사용자는 레포 주소에 관심이 없을거고 관심이 있는 사람은 이미 메인에서 봤을테니까 또 다른 곳에 만들기에는 디자인을 갈아 엎어야 하는 것도 있고 `/main/setting`같은 곳에 넣는것도 오히려 숨겨두는 것 같아서 의미가 흐려지네요

**Comment by yunochi** [comment]
저도 이건 굳이... 싶어요. UI적으로 이쁘게 넣을만한 곳이 없고, 레포주소에 관심 있는 사람은 처음 로그인 화면에서부터 봤을것 같아요.
