### ISSUE TITLE
모바일 환경에서 '익명 질문을 받지 않기'를 켜둔 질문함의 미트볼 버튼이 가려짐

### ISSUE THREAD

**Issue by kdh8219** [serafuku/neo-quesdon#65]
![Screenshot_20241203_073904_Firefox](https://github.com/user-attachments/assets/f738a7c7-ca1e-4cf8-9e44-f3e8f58ed38b)

**Comment by yunochi** [comment]
오 맙소사 😇

**Comment by Squarecat-meow** [comment]
이건... 말풍선이 아니라 다른 걸로 바꾸던가 해야겠네요 말풍선 보기엔 좋았지만 기능적으로는 별 거 없으니까 그냥 바꿔도 될 듯? 미나상 any ideas?

**Comment by yunochi** [comment]
말풍선 글자 사이즈 조금만 줄이고 미트볼 버튼 위치 밀면 어떨까...?

**Comment by Squarecat-meow** [comment]
#70 에서 고쳤어요!

**Comment by kdh8219** [comment]
현재 패치 적용된 상태인가요? 아직 문제 해결 안되서 여쭤봅니다

**Comment by yunochi** [comment]
v1.2.0 릴리즈에 적용 예정입니다.

**Comment by kdh8219** [comment]
![Screenshot_20241205_233523_Firefox](https://github.com/user-attachments/assets/794d19d6-134e-4252-aec2-b0e63ae4e07d)
작동은 하는 것 같은데 이번엔 프로필 한가운데를 가리네요
