### ISSUE TITLE
1.2.0 설정창 모바일 대응

### ISSUE THREAD

**Issue by kdh8219** [serafuku/neo-quesdon#84]
![Screenshot_20241205_233459_Firefox](https://github.com/user-attachments/assets/437a0da0-39ca-4e69-87b2-0dbbfcc2c419)
좌우로 잘리는 현상이 있습니다

**Comment by yunochi** [comment]
![Screenshot_20241206_014557_Firefox](https://github.com/user-attachments/assets/92b2fdf0-f054-4e14-86a4-4baefc5061b7)

제 환경에서는 잘 보여서 문제 없을줄 알았는데 아이고
