### ISSUE TITLE
mfm으로 인해 자동전송되는 노트의 해쉬테그와 링크가 이스케이프 되어버리는 현상

### ISSUE THREAD

**Issue by kdh8219** [serafuku/neo-quesdon#88]
https://serafuku.moe/notes/a1j1rw6nq6
   
![Screenshot_20241208_195440_Firefox](https://github.com/user-attachments/assets/69749a14-475b-4030-9e97-e06aa0018930)

**Comment by yunochi** [comment]
이것은 버그가 아니라 기능입니다. 
질문/답변에 커모지나 MFM문법을 사용할 수 있는건 의도된 사양이 맞고, 실제로 그렇게 쓰이기도 해서 이 동작을 없애기는 어려울 것 같아요.

**Comment by kdh8219** [comment]
알아서 `***`를 추가해준다던지 하는건 어떨까요?

**Comment by yunochi** [comment]
미스키에 같은 내용으로 노트를 작성할때도 동일하게 보이는 현상이라 무리하게 유저의 의도를 짐작해서 workaround 하는것 자체가 오히려 예외 케이스를 만나면 이상한 동작을 할 것 같습니다. 
아예 답변을 자동으로 `<plain>` 으로 감싸서 MFM으로 파싱되는걸 막을수는 있겠지만, MFM문법을 사용한 답변을 못 쓰게 된다는게 더 큰 단점일 것 같고요.

**Comment by kdh8219** [comment]
> 알아서 `***`를 추가해준다던지 하는건 어떨까요?

좀 더 자세하게 설명하자면, '유저가 작성한 mfm 테그가 닫혀있지 않으면 url과 해쉬테그로 번지지 않게 알아서 닫고 난 후 적는건' 어떨까요?

**Comment by yunochi** [comment]
이건 미스키의 MFM문법 해석에 한정된 동작이라 고쳐야 한다면 네오퀘스돈이 아니라 미스키 자체에서 수정하는게 맞을것 같아요.
