### ISSUE TITLE
유저를 차단할 때 이미 받은 질문들을 자동으로 거절하기

### ISSUE THREAD

**Issue by kdh8219** [serafuku/neo-quesdon#98]
새로 차단한 유저가 이미 질문해서 답변을 기다리고있는 질문들을 자동으로 거절하면 좋을 것 같습니다.
반대 동작(이미 한 질문 취소하기)은 악용 가능성이 있으니 구현하지 않는편이 좋을것이라고 생각합니다.

**Comment by yunochi** [comment]
네 아무래도 이 동작이 맞을것 같네요
